### ISSUE TITLE
Changes to the code adds extra formatting

### ISSUE THREAD

**Issue by Phillipus** [eclipse/gef-classic#109]
When I make a change in the GEF code and save it, it is formatted according to the `.settings` files. That's OK, but the problem is when you submit a PR it's harder to see the relevant diff amongst all the other changes. I guess we just have to live with it?

**Comment by azoitl** [comment]
The problem I have with the `.settings`files is that the settings there are a bit out dated. Therefore I created the PR #103 to use the default Eclipse settings. Not sure if this is a good idea. But as you point out above I think it would be a good idea to do one pull request with just reformatting all the java files to whatever setting we are choosing. I did the same in 4diac IDE and this reduced this formatting noise a lot and we got more modern formatted code.

**Comment by Phillipus** [comment]
Sounds like a good idea.

**Comment by azoitl** [comment]
Then I will do that after my current pull requests are merged. Probably will do that in the next days.

In 4diac IDE we have a common set of workspace settings that we share and import. This ensure the same formatting but we also have some save actions like clean-up and formating. Not sure if this is also something for GEF. I'll attach the 4diac settings here. Happy to get some feedback.

[4diacSettings.epf.txt](https://github.com/eclipse/gef-classic/files/9410189/4diacSettings.epf.txt)

Had to add the txt file ending otherwise Github was not happy.

**Comment by azoitl** [comment]
As discussed I just created PR #110, in which I reformatted all the Java files to the current default eclipse style. I hope this reduces the noise in future commits.
I sofar didn't do any automatic clean-ups that Eclipse would be capable of.

**Comment by azoitl** [comment]
With PR  #110 merged I tihnk it is safe to close this issue.

**Comment by Phillipus** [comment]
>With PR https://github.com/eclipse/gef-classic/pull/110 merged I tihnk it is safe to close this issue.

OK, thanks for the PR!
