### ISSUE TITLE
Can gef-classic be added to maven central?

### ISSUE THREAD

**Issue by peakschris** [eclipse/gef-classic#192]
We consume most of our artifacts from maven central, but the recent versions of draw2d are not there. Could they be maintained on maven central?

I've also noticed when uploading draw2d to our own private repository that it ends up with a SNAPSHOT version number. Could it be structured with a release version number?

**Comment by ptziegler** [comment]
I like the first one, even though for slightly different reasons. We use Tycho to retrieve the GAV coordinates of our p2 dependencies using Maven Central, in order to track their licenses. GEF is one project where we have to do this manually.

> I've also noticed when uploading draw2d to our own private repository that it ends up with a SNAPSHOT version number.

What do you mean by "upload to our private repository"? Do you clone the repository and then run a `mvn clean deploy`?

The reason you get the SNAPSHOT is because that's how Tycho handles the `.qualifier` in the Manifest. I don't think this something that is supported by the current release/build process. _However_ , if you build the project locally, you can always contribute your own "release-build-version" via the `-Dtycho.buildqualifier.format` environment variable.

From the [release notes](https://github.com/eclipse-tycho/tycho/blob/master/RELEASE_NOTES.md):
> What will result in the usual 1.0.0-SNAPSHOT for a regular mvn clean install, if you want to do a release, you can now simply call mvn -Dtycho.buildqualifier.format=yyyyMMddHHmm clean deploy and your artifact will get the 1.0.0-<formatted qualifier> version when published! This also is supported if you use pomless build.
