### ISSUE TITLE
Our p2 repository is in dire need of modernization

### ISSUE THREAD

**Issue by ptziegler** [eclipse/gef-classic#313]
Our current setup is quite rudimentary and prone to issues ~~such as acidentally deleting all releases~~.

I think we can do a better job. As far as I can tell, GEF fx is using [justj](https://eclipse.dev/justj/?page=tools) to host their artifacts. We should probably do the same.

I propose that we use https://download.eclipse.org/tools/gef/classic/updates as the new location for our artifacts.

@merks Given that you've already set this up for other projects, do you have any advice on what I have to take into consideration? Otherwise I'd give it a try within the next few days.

Because as far as I understand, the org.eclipse.justj.p2.manager already does most of the work for me, so I hope this is a straightforward configuration.

**Comment by merks** [comment]
This time you are one step ahead.  😜

I can help get this prototyped, if I know that folks are receptive.

**Comment by merks** [comment]
I have a prototype working locally. 

![image](https://github.com/eclipse/gef-classic/assets/208716/89d468a2-2279-4828-a736-974a5b1b18b5)

I feel it would be nicer if we just reused the `classic` folder directly:

https://download.eclipse.org/justj/?file=tools/gef/classic

Just like we use the `fx` folder directly:

https://download.eclipse.org/justj/?file=tools/gef/fx/

I think we could do that without breaking anything because if we move every that is under here:

https://download.eclipse.org/justj/?file=tools/gef/classic

to here instead:

https://archive.eclipse.org/justj/?file=tools/gef/classic

the download.eclipse.org servers 404 handler will just redirect any `https://download.eclipse.org/tools/gef/classic/releases/*` URL to `https://archive.eclipse.org/tools/gef/classic/releases/*` as if it were a mirror.

So no existing links would be broken.

As an added bonus. I believe all the existing releases can be copied into the new folder structure so that we can immediately have a complete structure with releases, milestones, and nightly builds.

Does that sound okay?

**Comment by ptziegler** [comment]
> So no existing links would be broken.

That's the only thing we definitely need to make sure.

Being able to keep the artifacts in _gef/classic_, rather than _gef/classic/updates_ sounds like a much cleaner solution. Especially if we are also able to migrate the already existing releases.

**Comment by merks** [comment]
What I've also tested is that we can keep the gef/classic/latest link which we manually point at gef/classic/nightly/latest.  I expect the same would work for gef/classic/releases/latest to point at gef/classic/release/latest but I've not tested that yet.  This way any hard version links will redirect to archive, and the two 'latest' links will link to latest nightly and latest release, as one would expect, so folks using those will not have to change anything either.

I will test fully.  The archive redirection definitely works as I described...

**Comment by merks** [comment]
Yes all that is workable as tested locally:

![image](https://github.com/eclipse/gef-classic/assets/208716/f4a1bc64-3f2d-47e4-a8a7-154383713ef6)

I.e., releases can be incorporated into the new structure and the two latest links can be manually created to compose the latest nightly and latest release.

So moving to the new structure will be effectively transparent to anyone using the existing URLs...

**Comment by merks** [comment]
The proof of concept is complete and tested by this job:

https://ci.eclipse.org/emf/job/test-gef-classic/

It promotes here:

https://download.eclipse.org/modeling/emf/emf/archive/gef/classic/release/index.html

(The displayed URLs on the generated pages are not actually correct because of the testing via EMF's ci instance.)

These two "legacy" URLs:

- https://download.eclipse.org/modeling/emf/emf/archive/gef/classic/latest/
- https://download.eclipse.org/modeling/emf/emf/archive/gef/classic/releases/latest/

function as "aliases" for

- https://download.eclipse.org/modeling/emf/emf/archive/gef/classic/nightly/latest/
- https://download.eclipse.org/modeling/emf/emf/archive/gef/classic/release/latest/

I will create a PR next week when I have commit rights and can more easily complete the tasks unassisted.  Of course you can look at the commit above to preview the up-coming changes.

@ptziegler @azoitl 

Do you have any outstanding concerns?

**Comment by ptziegler** [comment]
You're a national treasure! 😃
This looks great and should greatly streamline the release process.

**Comment by azoitl** [comment]
From what I understand it looks amazing. Thanks a lot @merks!

**Comment by merks** [comment]
I'm mostly done here:

https://download.eclipse.org/tools/gef/classic/

I had some problems with the sonar thing.  I'll look at that again in a while, but I probably need help...

**Comment by azoitl** [comment]
@merks thx a lot for this. I'm happy to support with sonar (if I'm able to).

One question. If I have a build/project that would use the nightly GEF Classic version what p2 repo link I should use now?

**Comment by ptziegler** [comment]
> One question. If I have a build/project that would use the nightly GEF Classic version what p2 repo link I should use now?

That would be https://download.eclipse.org/tools/gef/classic/nightly/latest

Side note: We also need to update the readme file...

**Comment by merks** [comment]
I tried those attributes originally but then the builds failed complaining about things I didn't understand...

I was going to try again in a few minutes...

**Comment by merks** [comment]
Note that I keep backups here:

https://download.eclipse.org/justj/?file=tools/gef/archive

but I think that entire folder can be deleted.

I copied content to this folder:

**Comment by merks** [comment]
FYI, I updated the links here:

https://projects.eclipse.org/projects/tools.gef/downloads

**Comment by merks** [comment]
@ptziegler @azoitl 

Unless I hear otherwise, I will delete this "backup" folder at the end of the day.

**Comment by ptziegler** [comment]
Sounds good to me. I don't think we'll need the milestone/release candidates so everything important seems be there.

**Comment by merks** [comment]
@ptziegler 

Speaking of those, I should probably remove them `RC*/M*` from archive.eclipse.org:

https://archive.eclipse.org/justj/?file=tools/gef/classic/releases

![image](https://github.com/eclipse/gef-classic/assets/208716/ebd85387-0c87-4f8b-9c66-8286e0b7ecae)

Folks should really only be using releases...

**Comment by merks** [comment]
@ptziegler @azoitl 

I would run this command:
```
+ cd /home/data/httpd/archive.eclipse.org/tools/gef/classic/releases
+ pwd
/home/data/httpd/archive.eclipse.org/tools/gef/classic/releases
+ echo rm -rf 3.15.0m1 3.15.0M1 3.15.0M3 3.16.0M1 3.16.0M2 3.16.0M3 3.17.0M1 3.17.0M2 3.17.0M3 3.18.0M1 3.18.0M2 3.15.0RC1 3.16.0RC1 3.16.0RC2 3.17.0RC1 3.18.0RC1
rm -rf 3.15.0m1 3.15.0M1 3.15.0M3 3.16.0M1 3.16.0M2 3.16.0M3 3.17.0M1 3.17.0M2 3.17.0M3 3.18.0M1 3.18.0M2 3.15.0RC1 3.16.0RC1 3.16.0RC2 3.17.0RC1 3.18.0RC
```

I .e., rebuild this job, but without the `echo` in front of the `rm -rf`:

https://ci.eclipse.org/gef/job/genie.gef-ssh/22/

I'll do that tomorrow, unless someone expresses concerns.

**Comment by azoitl** [comment]
I'm a big fan of cleaning that up. 

On a site note how we are now doing Milestone RC and Releases?

**Comment by merks** [comment]
Fortunately @ptziegler  is verify familiar with how this works because that's how he produces the window builder site:

https://download.eclipse.org/windowbuilder/updates/

Basically just use the dropdown to pick milestone (where it says nightly as the default choice):

![image](https://github.com/eclipse/gef-classic/assets/208716/7329ce5b-0e41-47c9-a568-37a92d7679e9)

For a release, it does a full build, but does not promote the build.  Rather it mirrors the most recent milestone to become the release.  But as I said, @ptziegler  is familiar with the process and of course I'm happy to answer any questions.

I suggest reading this as it explains details such as how the milestones are self-cleaning:

https://eclipse.dev/justj/?page=tools#p2-anatomy

**Comment by azoitl** [comment]
Thanks for the reading pointer. I definitely want to learn more on this topic.

**Comment by ptziegler** [comment]
As Ed said, the `nightly` parameter promotes to https://download.eclipse.org/tools/gef/classic/nightly, the `milestone` parameter to https://download.eclipse.org/tools/gef/classic/milestone and the `release` parameter takes the latest milestone build and promotes it to https://download.eclipse.org/tools/gef/classic/release

You just have to pick the one for the type of build you want to do and the rest should be done in the background.

A few caveats:

- We don't distinguish between milestones and release candidates, which are both promoted to `/milestone`
- Once you build the first milestone of the upcoming release, all previous milestones are deleted. Meaning by then, they should no longer be referenced in e.g. the simrel repository.
- Even though the `release` job only promotes the latest milestone, it still also does a full build/test of the project. This might be a little confusing at first, but those artifacts are simply ignored.

**Comment by merks** [comment]
@ptziegler 

That's all exactly right. 😁 

I've done the final cleanup so I believe this issue can be closed as completed now...

**Comment by azoitl** [comment]
Did my first Milestone contribution. I like the way it is working. Feels much saver.

**Comment by merks** [comment]
So I think this issue could be closed, unless someone has another task in mind...

**Comment by azoitl** [comment]
I would think so. @ptziegler any objections?

Thx again @merks and @ptziegler for the work here.

**Comment by merks** [comment]
Now that I follow the repo I see that you and @ptziegler do an **impressive** amount of work to modernize and improve GEF so I'm very happy to help make life easier on at least one front!

**Comment by ptziegler** [comment]
No objects from my side. Thank you a lot for this great job, Ed!
