### ISSUE TITLE
Suppressing all potential static method warnings

### ISSUE THREAD

**Issue by Phillipus** [eclipse/gef-classic#367]
Would it be better to suppress these warnings in each project's `.settings/org.eclipse.jdt.core.prefs` file with:

`org.eclipse.jdt.core.compiler.problem.reportMethodCanBePotentiallyStatic=ignore`

rather than adding a `@SuppressWarnings("static-method")` annotation to the method?

**Comment by azoitl** [comment]
I'm strongly against this. I on purpose enabled the warning. I know it creates a bit of noise now. However I found several places where static is the better option. I also found several places which should have been static in the beginning. But now cannot be turned static anymore because of API restrictions. However for any new code I find it much better to explicitly state per method that it shouldn't be static.
