### ISSUE TITLE
ViewportAutoexposeHelper is very intensive on CPU

### ISSUE THREAD

**Issue by Phillipus** [eclipse/gef-classic#492]
The [ViewportAutoexposeHelper](https://github.com/eclipse/gef-classic/blob/master/org.eclipse.gef/src/org/eclipse/gef/editparts/ViewportAutoexposeHelper.java) consumes a lot of CPU if you hover a creation tool near the edge of the Viewport.

1. Add a debug line `System.out.println(where);` to the `public boolean step(Point where)` method so you can see when it's called
2. Select a creation tool from the Palette
3. Hover your mouse near the edge of the viewport
4. Watch many calls being made to `ViewportAutoexposeHelper#step` and the CPU usage rise in System monitor

I don't know if this could be optimised somehow to be less busy?

**Comment by ptziegler** [comment]
Main culprit seems to be the the following methods, which mercilessly fires one update after the other:

https://github.com/eclipse/gef-classic/blob/a9f29fd0ad586397e45c0223908c6b0b72e9cb3f/org.eclipse.gef/src/org/eclipse/gef/tools/TargetingTool.java#L98-L108

https://github.com/eclipse/gef-classic/blob/a9f29fd0ad586397e45c0223908c6b0b72e9cb3f/org.eclipse.gef/src/org/eclipse/gef/tools/TargetingTool.java#L347-L354

There was a similar discussion [here](https://github.com/eclipse/gef-classic/issues/430) which is why I'd propose a similar approach: To copy the JFace [Throttler](https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.jface/src/org/eclipse/jface/util/Throttler.java) class to Draw2D and then add a delay between the updates. 

The updates are already done asynchronously, so the only difference would be that instead of e.g. every 1ms, the methods are called every 100ms.

**Comment by ptziegler** [comment]
I forgot that those classes are in the GEF bundle, so we can already use the Throttler class without adding any new dependencies. 🎉 

See https://github.com/eclipse/gef-classic/pull/494.

**Comment by Phillipus** [comment]
That was quick! :-)

I tested it and it improves the polling rate. The only thing is that when the viewport scrolls into view it's a bit more jerky and not so smooth.

I wonder if there is another way to optimise this by not making the calls if the viewport is currently scrolled into view?

**Comment by Phillipus** [comment]
I set the value to 1ms in the Throttler and the CPU usage is way down even though this is a low value. So perhaps the Throttler is doing something to pace things?

**Comment by Phillipus** [comment]
> I set the value to 1ms in the Throttler and the CPU usage is way down even though this is a low value. So perhaps the Throttler is doing something to pace things?

Yep, after more testing a value of 1ms in the Throttler works great.

**Comment by Phillipus** [comment]
This does effectively the same thing as the Throttler:

```java
Display.getCurrent().asyncExec(new QueuedAutoexpose());
try {
    Thread.sleep(1);
}
catch(InterruptedException ex) {}
```

**Comment by ptziegler** [comment]
> I set the value to 1ms in the Throttler and the CPU usage is way down even though this is a low value. So perhaps the Throttler is doing something to pace things? Or perhaps the old method was even faster than 1ms?

It wouldn't surprise me that with values this low, you're slowly 

> This does effectively the same thing as the Throttler:
> 
> ```java
> Display.getCurrent().asyncExec(new QueuedAutoexpose());
> try {
>     Thread.sleep(1);
> }
> catch(InterruptedException ex) {}
> ```

I don't think blocking the whole UI thread for a millisecond is a good idea... A more accurate alternative would be:

`Display.getCurrent().timerExec(1, new QueuedAutoexpose())`

**Comment by Phillipus** [comment]
> A more accurate alternative would be:

`Display.getCurrent().timerExec(1, new QueuedAutoexpose())`

Unfortunately, that doesn't work at all, I guess because it's not async?

**Comment by Phillipus** [comment]
Now after some coffee, let's try that again...

> A more accurate alternative would be:

`Display.getCurrent().timerExec(1, new QueuedAutoexpose());`

That's perfect! I tested on Windows and Mac and that does the trick. A value of 1 or 2 works well.

**Comment by Phillipus** [comment]
I've tested `Display.getCurrent().timerExec(delayValue, new QueuedAutoexpose());` on Mac and Windows and I think it offers the best, and least intrusive, solution. However with a `delayValue` of 1 on Mac, scrolling is too slow. Testing with Mac and Windows the best value is between 5 and 10 ms. For Archi, I'm going to go with this solution and decide between 5 or 10 ms.

**Comment by ptziegler** [comment]
I spent some more time thinking about this problem and ideally, I'd like this to be an opt-in behavior. We had way too many occurrences where seemingly trivial changes broke some obscure workflow.

So instead, people can now specify a `org.eclipse.gef.throttlerDuration` system property to set whatever duration they like. Or none at all, which replicates the current behavior. If people use it and if the feedback is good, it might be worth considering initializing this with a non-zero value, but that's a discussion for a later time.

**Comment by Phillipus** [comment]
That's way too complicated. I'm out.

**Comment by ptziegler** [comment]
I really hope it isn't :sweat_smile:... If you want to have a 1ms interval, you use `-Dorg.eclipse.gef.throttlerDuration=1`, for 5ms you use `-Dorg.eclipse.gef.throttlerDuration=5` and so on.

**Comment by Phillipus** [comment]
I'll stick with my own fork of GEF. Bye.

**Comment by azoitl** [comment]
@Phillipus I'm sorry that you see it like this. I really enjoyed our discussions and your feedback and bug reports where very value able for improving GEF Classic. I can understand that for you sticking with your fork is easier. But I don't think that this is a sustainable solution for all of us. I personally believe that our open collaboration on the official GEF Classic will lead to a better solution for all in the end. However this currently comes at a price that we are currently much slower then I would like to be. I myself broke several GEF Classic clients because I was not careful enough. @ptziegler very often showed to way to a more reliable and backward compatible solution. Therefore having options to opt in and out for not breaking the numerous applications of GEF Classic  is an important point.

**Comment by Phillipus** [comment]
> @Phillipus I'm sorry that you see it like this. I really enjoyed our discussions and your feedback and bug reports where very value able for improving GEF Classic. I can understand that for you sticking with your fork is easier. But I don't think that this is a sustainable solution for all of us. I personally believe that our open collaboration on the official GEF Classic will lead to a better solution for all in the end. However this currently comes at a price that we are currently much slower then I would like to be. I myself broke several GEF Classic clients because I was not careful enough. @ptziegler very often showed to way to a more reliable and backward compatible solution. Therefore having options to opt in and out for not breaking the numerous applications of GEF Classic is an important point.

Regarding this issue and the proposed PR https://github.com/eclipse/gef-classic/pull/494 from @ptziegler - Yes, it's a very thorough and safe implementation but, for me, it's too complicated adding a `Throttler` and yet another system property. I find the one-liner in https://github.com/eclipse/gef-classic/issues/492#issuecomment-2255362109 fixes the problem.

I'm afraid I'm stuck with my fork for now because I made too many changes to the GEF/Draw2d core, some of which are not suitable for others. When I get some time in the future I need to merge all the changes from here onto my fork and see if I can either get some of those changes added here or add them some other how.
